# Generated by Django 4.2.22 on 2025-06-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BurningEventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConservationUnitCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManagementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('regional_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firedata.regionalgroup')),
            ],
        ),
        migrations.CreateModel(
            name='ConservationUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('area_in_uc', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('percent_fire_affected_in_uc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='firedata.conservationunitcategory')),
                ('management_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firedata.managementunit')),
                ('regional_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firedata.regionalgroup')),
            ],
        ),
        migrations.CreateModel(
            name='BurningEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wildfire_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prescribed_burn_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('controlled_burn_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('firebreak_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('natural_fire_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isolated_indigenous_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_prevention_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_firefighting_area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categories', models.ManyToManyField(blank=True, to='firedata.burningeventcategory')),
                ('conservation_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firedata.conservationunit')),
            ],
        ),
    ]
